#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other POSIX shell available, try using that.
#   (2) Now that POSIX shell issue is dealt with, run:
#
#       * $ chmod +x gradlew
#
#   * $ ./gradlew <some task>
#
#   That is where the magic happens.
#
#   If you don't have a POSIX compliant shell, you could use Java's
#   Runtime.exec() method to run this script, or use the NT version gradlew.bat.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}   # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="gradle-wrapper.jar"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/$APP_JAR

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor count"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor count to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygwin_path "$APP_HOME" )
    CLASSPATH=$( cygwin_path "$CLASSPATH" )

    JAVACMD=$( cygwin_path "$JAVACMD" )

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$( find -L / -maxdepth 3 -type d -name root 2>/dev/null )
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGWIN_MODULE" != "" ] ; then
        ROOTDIRSRAW="$ROOTDIRSRAW|$GRADLE_CYGWIN_MODULE"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=$( echo "$arg"|egrep -c "$ROOTDIRSRAW" ) || CHECK=0
        CHECK2=$( echo "$arg"|egrep -c "^-" ) || CHECK2=0
        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then
             arg=$( cygpath -p -f - <<<"$arg")
        fi
        # Roll the args list around again to pick up the new arg
        set -- "$@" "$arg"
        shift
    done
fi

# It is recommended to use the OG exec to replace the current shell with the Java process so that the JVM shuts down on script termination.
# Executing without the exec is a security issue because you are creating separate child processes that can escape the script's reach.
# However, when dealing with MinGw (MSYS), the generated wrapper scripts (.bat and .cmd) references Java from a Windows perspective and thus needs more flexibility.
# A workaround for this is to use the -Dbasedir flag and rely on it rather than on $PWD and basedir of the Gradle wrapper.
if ! "$cygwin" && ! "$msys" ; then
    exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
        -classpath "$CLASSPATH" \
        -Dorg.gradle.appname=$APP_BASE_NAME \
        -Dorg.gradle.wrapper.properties="$jardir/gradle-wrapper.properties" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
else
    # For Cygwin or MSYS, use the same command with Windows line endings, passed via -Dbasedir
    WDIR=$( cygpath -w "$APP_HOME" )
    cmd /C "
        $JAVACMD $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
        -classpath \"$CLASSPATH\" \
        -Dorg.gradle.appname=$APP_BASE_NAME \
        -Dbasedir=\"$WDIR\" \
        org.gradle.wrapper.GradleWrapperMain \
        \"$@\"
    " "$@"

fi

# By default we should be in the correct project dir, but when run from Elsewhere some shell think s we are in
# the wrong directory so we may have to change it
if [ "$(pwd)" != "$(dirname "$0")" ] ; then
    cd "$(dirname "$0")" || exit
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    -Dorg.gradle.appname=$APP_BASE_NAME \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
