name: Android Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract repository name
        id: repo-name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
        
      - name: Extract version name
        id: version_name
        run: |
          VERSION_NAME=$(grep -oP 'versionName\s*=\s*"\K[^"]+' ./app/build.gradle.kts)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
              
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Install Android Build Tools
        run: sdkmanager "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        shell: bash
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      
      - name: Sign APK
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            ${{ secrets.KEYSTORE_ALIAS }}
          rm keystore.jks

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk ${{ env.REPO_NAME }}-v${{ env.VERSION_NAME }}-${{ github.run_number }}.apk
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
          tag: v${{ env.VERSION_NAME }}-${{ github.run_number }}
          prerelease: true
